### ISSUE TITLE
node_modules/readline-sync/lib/read.sh: Permission denied

### ISSUE THREAD

**Issue by raine** [anseki/readline-sync#13]
Got this when running a cli app installed to home directory.

```
> child_process.js:1362
    throw err;
          ^
Error: Command failed: /bin/sh -c "/home/rainevi/node_modules/ez-jenkins/node_modules/readline-sync/lib/read.sh"
/bin/sh: /home/rainevi/node_modules/ez-jenkins/node_modules/readline-sync/lib/read.sh: Permission denied

    at checkExecSyncError (child_process.js:1339:13)
    at Object.execFileSync (child_process.js:1359:13)
    at _readlineShell (/home/rainevi/node_modules/ez-jenkins/node_modules/readline-sync/lib/readline-sync.js:103:29)
    at _readlineSync (/home/rainevi/node_modules/ez-jenkins/node_modules/readline-sync/lib/readline-sync.js:58:19)
    at Object.exports.prompt (/home/rainevi/node_modules/ez-jenkins/node_modules/readline-sync/lib/readline-sync.js:208:10)
    at module.exports (/home/rainevi/node_modules/ez-jenkins/lib/cli/setup.js:10:25)
    at Object.<anonymous> (/home/rainevi/node_modules/ez-jenkins/lib/cli/index.js:32:23)
    at Object.<anonymous> (/home/rainevi/node_modules/ez-jenkins/lib/cli/index.js:34:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

System:

```
Linux version 2.6.32-431.20.3.el6.x86_64 (mockbuild@c6b9.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Thu Jun 19 21:14:45 UTC 2014
```

It starts working if you `chmod +x` the script.

**Comment by anseki** [comment]
Hi raine, Thank you for your report.
A cause of this problem is `-c`, not permission. (Node v0.11+)
I fixed it.
