### ISSUE TITLE
demo  error

### ISSUE THREAD

**Issue by ArvoGuo** [anseki/readline-sync#15]
```
var readlineSync = require('readline-sync'),
  chalk = require('chalk'),
  user, pw, command;

readlineSync.setPrint(function(display, encoding) {
  logger.log(chalk.stripColor(display)); // Remove control characters.
});

console.log(chalk.black.bold.bgYellow('    Your Account    '));
user = readlineSync.question(chalk.gray.underline(' USER NAME ') + ' :');
pw = readlineSync.question(chalk.gray.underline(' PASSWORD  ') + ' :', {noEchoBack: true});
// Authorization ...
console.log(chalk.green('Welcome, ' + user + '!'));

readlineSync.setPrompt(chalk.red.bold('> '));
command = readlineSync.prompt();
```

```
/Users/Arvo/github/test/test.readlineSync.js:6
  logger.log(chalk.stripColor(display)); // Remove control characters.
  ^
ReferenceError: logger is not defined
    at /Users/Arvo/github/test/test.readlineSync.js:6:3
    at _readlineSync (/Users/Arvo/github/test/node_modules/readline-sync/lib/readline-sync.js:116:7)
    at Object.exports.question (/Users/Arvo/github/test/node_modules/readline-sync/lib/readline-sync.js:380:10)
    at Object.<anonymous> (/Users/Arvo/github/test/test.readlineSync.js:10:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

```

what is logger?
need require('logger')?

**Comment by anseki** [comment]
Hi ArvoGuo
Because that is a sample for the Logger, of course an error is thrown if you don't have the Logger. See description on README.
The Logger is the library for logging.
e.g. log4js is very popular one.
https://github.com/nomiddlename/log4js-node
Or
https://www.npmjs.com/search?q=logger

Anyway, if you want to let that sample run without the Logger, add this code at top of the sample code:

```js
var logger = {log: function(msg) { console.log('[LOG] ' + msg); }};
```

**Comment by ArvoGuo** [comment]
thank you very much .  it helps. 
I'm new here.
