### ISSUE TITLE
The platform doesn't support interactive reading [Win7 x64]

### ISSUE THREAD

**Issue by seiya-git** [anseki/readline-sync#19]
Hello, It's me again. On win 7 I get this error, but on Win 10 all ok.
![Screenshot](http://ipic.su/img/img7/fs/kiss_233kb.1440945170.png)
```javascript
C:\hardsub_avisynth\tools\js_scripts\node_modules\readline-sync\lib\readline-sync.js:66
    if (res.error) { throw res.error; }
                     ^

Error: The platform doesn't support interactive reading
    at readlineExt (C:\hardsub_avisynth\tools\js_scripts\node_modules\readline-sync\lib\readline-sync.js:268:19)
    at tryExt (C:\hardsub_avisynth\tools\js_scripts\node_modules\readline-sync\lib\readline-sync.js:65:15)
    at C:\hardsub_avisynth\tools\js_scripts\node_modules\readline-sync\lib\readline-sync.js:164:15
    at _readlineSync (C:\hardsub_avisynth\tools\js_scripts\node_modules\readline-sync\lib\readline-sync.js:224:5)
    at getValidLine (C:\hardsub_avisynth\tools\js_scripts\node_modules\readline-sync\lib\readline-sync.js:724:11)
    at exports.question (C:\hardsub_avisynth\tools\js_scripts\node_modules\readline-sync\lib\readline-sync.js:800:10)
    at Object.<anonymous> (C:\hardsub_avisynth\tools\js_scripts\psp_encoder.js:130:12)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
```

**Comment by anseki** [comment]
Hi seiya-git, thanks again.
This seems a bug of Windows PowerShell. Some versions of PowerShell fail when the key is pushed before it's ready. When you type key after the query-message is shown, it will work fine.
I made PowerShell retry after it fails.
Could you check please?

**Comment by seiya-git** [comment]
thank you again, everything seems to be working fine :3

**Comment by anseki** [comment]
Thank you for checking. I think that this problem was solved.
