### ISSUE TITLE
Error in `e.stderr.trim();`

### ISSUE THREAD

**Issue by Darker** [anseki/readline-sync#30]
D:\web\resourcerefresher\node_modules\readline-sync\lib\readline-sync.js:269
          extMessage = e.stderr.trim();
                               ^
    
    TypeError: Cannot read property 'trim' of undefined
        at readlineExt (D:\web\resourcerefresher\node_modules\readline-sync\lib\readline-sync.js:269:28)
        at tryExt (D:\web\resourcerefresher\node_modules\readline-sync\lib\readline-sync.js:65:15)
        at D:\web\resourcerefresher\node_modules\readline-sync\lib\readline-sync.js:166:15
        at _readlineSync (D:\web\resourcerefresher\node_modules\readline-sync\lib\readline-sync.js:226:5)
        at getValidLine (D:\web\resourcerefresher\node_modules\readline-sync\lib\readline-sync.js:726:11)
        at Object.exports.question (D:\web\resourcerefresher\node_modules\readline-sync\lib\readline-sync.js:802:10)
        at getFiles (D:\web\resourcerefresher\refresh.js:21:29)
        at ReadStream.<anonymous> (D:\web\resourcerefresher\refresh.js:8:31)
        at emitOne (events.js:77:13)
        at ReadStream.emit (events.js:169:7)

It's sad when error handling code causes errors.

**Comment by anseki** [comment]
Hi @Darker, thank you for your report.
I will update readlineSync soon.
